# Generated by Django 5.2.6 on 2025-09-10 15:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the project was created')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent (must be greater than 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.CharField(help_text='Description of the expense', max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when the expense occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the expense was recorded')),
                ('project', models.ForeignKey(help_text='Project this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
